FROM confluentinc/cp-kafka-connect:7.4.0-2-ubi8
COPY target/kafka-connect-ably-msk-plugin/kafka-connect-target /plugins/

ADD bin/docker-entrypoint.sh /bin/docker-entrypoint.sh
ENTRYPOINT ["/bin/docker-entrypoint.sh"]
